version: "3"

services:
  wppconnect-1:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    mem_limit: 1g
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
    image: wppconnect-server
    environment:
      - SECRET_KEY=$SECRET_KEY
      - WEBHOOK_URL=$WEBHOOK_URL
      - SERVER_PORT=$SERVER_PORT
      - POWERED_BY=$POWERED_BY
    ports:
      - 21469:21465

  wppconnect-2:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    mem_limit: 1g
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
    image: wppconnect-server
    environment:
      - SECRET_KEY=$SECRET_KEY
      - WEBHOOK_URL=$WEBHOOK_URL
      - SERVER_PORT=$SERVER_PORT
      - POWERED_BY=$POWERED_BY
    ports:
      - 21466:21465

  wppconnect-3:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    mem_limit: 1g
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
    image: wppconnect-server
    environment:
      - SECRET_KEY=$SECRET_KEY
      - WEBHOOK_URL=$WEBHOOK_URL
      - SERVER_PORT=$SERVER_PORT
      - POWERED_BY=$POWERED_BY
    ports:
      - 21467:21465

  wppconnect-4:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    mem_limit: 1g
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
    image: wppconnect-server
    environment:
      - SECRET_KEY=$SECRET_KEY
      - WEBHOOK_URL=$WEBHOOK_URL
      - SERVER_PORT=$SERVER_PORT
      - POWERED_BY=$POWERED_BY
    ports:
      - 21468:21465

volumes:
  wppconnect_tokens: {}      