version: '3'

services: 

  wppconnect-server-1:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=$SECRET_KEY
      - WEBHOOK_URL=$WEBHOOK_URL
      - SERVER_PORT=$SERVER_PORT
    restart: always
    env_file:
      - .env
    image: wppconnect-server
    container_name: wppconnect-server-1
    hostname: wppconnect-server
    networks: 
      wpp-network:
        ipv4_address: 172.20.0.2
    tty: true   
    
  wppconnect-nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: wppconnect-nginx
    hostname: wppconnect-nginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - "3591:3591"
    networks: 
      wpp-network:
        ipv4_address: 172.20.0.15   
    depends_on:
      - wppconnect-server-1

networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16